name: CI/CD for CalculatorApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore CalculatorApp/CalculatorApp.csproj

      - name: Build project
        run: dotnet build CalculatorApp/CalculatorApp.csproj --no-restore

      - name: Run tests
        run: dotnet test CalculatorTests/CalculatorTests.csproj --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Publish application
        run: dotnet publish CalculatorApp/CalculatorApp.csproj -c Release -o out

      - name: Deploy
        run: |
          mkdir -p ~/deploy
          cp -r out/* ~/deploy/
